name: spi-form-ui-model

on:
  push:
    branches:
      - prod  # Change this to your deployment branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x  # Use the required Node.js version for your project

    - name: Install Dependencies
      run: npm i --force

    - name: Build - spi-form-ui-model
      run: |
           export CI=false
           npm run build

    - name: Delete Existing S3 Objects - spi-form-ui-model
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SPI_FORM_UI_S3_BUCKET_MODEL: ${{ secrets.SPI_FORM_UI_S3_BUCKET_MODEL }}
      run: |
        aws s3 rm s3://$SPI_FORM_UI_S3_BUCKET_MODEL --recursive --region $AWS_REGION

    - name: Deploy to S3 - spi-form-ui-model
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SPI_FORM_UI_S3_BUCKET_MODEL: ${{ secrets.SPI_FORM_UI_S3_BUCKET_MODEL }}
      run: |
        aws s3 sync build/ s3://$SPI_FORM_UI_S3_BUCKET_MODEL --region $AWS_REGION --acl public-read
